use_pd_ctrl: false
use_joint_name: true
num_of_actuation_joint: 31

enable_configurable_thread_priority: false
motor_state_to_joint_state_thread_priority: 94
joint_cmd_to_motor_cmd_thread_priority: 95

joints_name: ["left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint", "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
              "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint", "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
              "waist_roll_joint", "waist_pitch_joint", "waist_yaw_joint",
              "head_yaw_joint", "head_pitch_joint",
              "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint", 
              "left_hand_yaw_joint", "left_hand_roll_joint", "left_hand_pitch_joint",
              "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint", 
              "right_hand_yaw_joint", "right_hand_roll_joint", "right_hand_pitch_joint"]