transition_steps: 2000

stand_pos:
  left_hip_pitch_joint: -0.25
  left_hip_roll_joint: 0.0
  left_hip_yaw_joint: 0.0
  left_knee_joint: 0.55
  left_ankle_pitch_joint: -0.30
  left_ankle_roll_joint: 0.0
  right_hip_pitch_joint: -0.25
  right_hip_roll_joint: 0.0
  right_hip_yaw_joint: 0.0
  right_knee_joint: 0.55
  right_ankle_pitch_joint: -0.30
  right_ankle_roll_joint: 0.0
  waist_yaw_joint: 0.0
  waist_roll_joint: 0.0
  waist_pitch_joint: 0.0
  left_shoulder_pitch_joint: 0.10
  left_shoulder_roll_joint: 0.10
  left_shoulder_yaw_joint: -0.20
  left_elbow_joint: -0.20
  left_wrist_yaw_joint: 0.0
  left_wrist_pitch_joint: 0.0
  left_wrist_roll_joint: 0.0
  right_shoulder_pitch_joint: 0.10
  right_shoulder_roll_joint: -0.10
  right_shoulder_yaw_joint: 0.20
  right_elbow_joint: -0.20
  right_wrist_yaw_joint: 0.0
  right_wrist_pitch_joint: 0.0
  right_wrist_roll_joint: 0.0
  head_yaw_joint: 0.0
  head_pitch_joint: 0.0

stand_kp:
  left_hip_pitch_joint: 580.0
  left_hip_roll_joint: 500.0
  left_hip_yaw_joint: 500.0
  left_knee_joint: 660.0
  left_ankle_pitch_joint: 400.0
  left_ankle_roll_joint: 400.0
  right_hip_pitch_joint: 580.0
  right_hip_roll_joint: 500.0
  right_hip_yaw_joint: 500.0
  right_knee_joint: 660.0
  right_ankle_pitch_joint: 400.0
  right_ankle_roll_joint: 400.0
  waist_yaw_joint: 800.0
  waist_roll_joint: 800.0
  waist_pitch_joint: 800.0
  left_shoulder_pitch_joint: 80.0
  left_shoulder_roll_joint: 80.0
  left_shoulder_yaw_joint: 80.0
  left_elbow_joint: 50.0
  left_wrist_yaw_joint: 40.0
  left_wrist_pitch_joint: 20.0
  left_wrist_roll_joint: 10.0
  right_shoulder_pitch_joint: 80.0
  right_shoulder_roll_joint: 80.0
  right_shoulder_yaw_joint: 80.0
  right_elbow_joint: 50.0
  right_wrist_yaw_joint: 40.0
  right_wrist_pitch_joint: 20.0
  right_wrist_roll_joint: 10.0
  head_yaw_joint: 10.0
  head_pitch_joint: 10.0

stand_kd:
  left_hip_pitch_joint: 8.0
  left_hip_roll_joint: 6.0
  left_hip_yaw_joint: 6.0
  left_knee_joint: 8.0
  left_ankle_pitch_joint: 2.0
  left_ankle_roll_joint: 2.0
  right_hip_pitch_joint: 8.0
  right_hip_roll_joint: 6.0
  right_hip_yaw_joint: 6.0
  right_knee_joint: 8.0
  right_ankle_pitch_joint: 2.0
  right_ankle_roll_joint: 2.0
  waist_yaw_joint: 8.0
  waist_roll_joint: 8.0
  waist_pitch_joint: 8.0
  left_shoulder_pitch_joint: 3.0
  left_shoulder_roll_joint: 3.0
  left_shoulder_yaw_joint: 2.0
  left_elbow_joint: 3.0
  left_wrist_yaw_joint: 2.0
  left_wrist_pitch_joint: 1.0
  left_wrist_roll_joint: 1.0
  right_shoulder_pitch_joint: 3.0
  right_shoulder_roll_joint: 3.0
  right_shoulder_yaw_joint: 2.0
  right_elbow_joint: 3.0
  right_wrist_yaw_joint: 2.0
  right_wrist_pitch_joint: 1.0
  right_wrist_roll_joint: 1.0
  head_yaw_joint: 1.0
  head_pitch_joint: 1.0
